---
# Tareas del rol para instalar y configurar NGINX
- name: Instalar NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copiar archivo de configuración personalizado
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Reiniciar el servicio de NGINX
  service:
    name: nginx
    state: restarted


    - import_tasks: validate.yml
